#!/usr/bin/env php
<?php
/**
 * Fusion - PHP Package Manager
 * Copyright © Valvoid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

use Valvoid\Fusion\Box\Box;
use Valvoid\Fusion\Fusion;
use Valvoid\Fusion\Log\Events\Errors\Error as InternalError;
use Valvoid\Fusion\Log\Events\Event;
use Valvoid\Fusion\Log\Events\Level;
use Valvoid\Fusion\Log\Serializers\Streams\Terminal\Terminal;
use Valvoid\Fusion\Options\Paths;
use Valvoid\Fusion\Options\Version;
use Valvoid\Fusion\Settings\Config;

spl_autoload_register(loadLazyCode(...));

try {
    $options = getopt("vhp", ["version", "help", "paths"]);

    if ($options)
        switch (array_key_first($options)) {
            case 'version':
            case 'v':
                $version = (new Box)
                    ->get(Version::class);

                echo " ___ _   _ ___ ___ ___  _  _" .
                    "\n| __| | | / __|_ _/ _ \| \| |" .
                    "\n| _|| |_| \__ \| | (_) | .` |" .
                    "\n|_|  \___/|___/___\___/|_|\_|" .
                    "\n\n\033[4;32mFusion - PHP Package Manager\033[0m" .
                    "\nversion $version->semver\n\n";
                exit;

            case 'paths':
            case 'p':
                $paths = (new Box)
                    ->get(Paths::class);

                echo "\n\033[4;32mroot, config, state, and cache paths\033[0m" .
                    "\n$paths->path" .
                    "\n$paths->config" .
                    "\n$paths->state" .
                    "\n$paths->cache\n\n";
                exit;

            case 'help':
            case 'h': showHelp(0);
            default: showHelp();
        }

    // remove filename
    array_shift($argv);
    $argv = array_filter($argv, fn ($argument) =>

        // flag options only for now
        // drop all with dash
        $argument[0] !== '-');

    $arguments = [];
    $command = array_shift($argv) ??
        showHelp();

    // inflate inline config
    foreach ($argv as $argument) {
        $argumentParts = explode('=', $argument, 2);

        if (!$argumentParts[0])
            throwError(
                "Invalid '$argument' argument. An argument " .
                "must be a non-empty 'key=value' entry."
            );

        $path = preg_split('/(?<!\\\\)\./', $argumentParts[0]);

        if ($command != "config" && $path[0] != "dir" &&
            $path[0] != "persistence" && $path[0] != "log" &&
            $path[0] != "hub")
            $path = ["tasks", $command, ...$path];

        // handle bool value
        if (!isset($argumentParts[1]))
            $argumentParts[1] = "";

        elseif ($argumentParts[1] == "false")
            $argumentParts[1] = false;

        elseif ($argumentParts[1] == "true")
            $argumentParts[1] = true;

        // reset value
        elseif ($argumentParts[1] == "null" ||
            $argumentParts[1] == "")
            $argumentParts[1] = null;

        inflateArgumentValue($arguments, $path, $argumentParts[1]);
    }

    if ($command == "config") {
        $config = (new Box)
            ->get(Config::class);

        echo "\n\033[4;32m$config->file\033[0m";

        if ($arguments) {
            echo "\n" . json_encode($arguments, JSON_PRETTY_PRINT |
                    JSON_UNESCAPED_SLASHES);

            $config->persist($arguments);

        } else echo "\n" . ($config->getContent() ??
            "No config yet.");

    } else {
        $fusion = (new Box)->get(Fusion::class,

            // runtime config
            config: $arguments);

        // Fusion uses own callback
        // tasks are complex and may result in code shifts
        spl_autoload_unregister(loadLazyCode(...));

        if ($fusion->execute($command) === false) {
            echo "\n\n";
            exit(1);
        }
    }

// own CLI and fusion constructor loggable
} catch (Event $event) {
    $terminal = new Terminal(["threshold" => Level::INFO]);

    $terminal->log(Level::ERROR, $event);
    echo "\n\n";
    exit(1);

// default
} catch (Exception $exception) {
    echo $exception->getMessage();
    echo $exception->getTraceAsString();
    echo "\n\n";
    exit(1);
}

echo "\n\n";
exit;

/**
 * Inflates inline argument value.
 *
 * @param array $config Pointer inside runtime config.
 * @param array $path Inline config path.
 * @param mixed $value Value.
 */
function inflateArgumentValue(mixed &$config, array $path, mixed $value): void
{
    $key = array_shift($path);
    $key = str_replace("\.", '.', "" . $key);

    if ($key) {
        if (!isset($config[$key]))
            $config[$key] = null;

        elseif (!is_array($config[$key]))
            $config[$key] = [
                $config[$key]
            ];

        inflateArgumentValue($config[$key], $path, $value);

    // extend
    } elseif (is_array($config))
        $config[] = $value;

    // add
    else $config = $value;
}

function showHelp(int $code = 1): void
{
    echo "\n\033[4;32musage\033[0m" .
        "\nfusion [command] ?args       Workload with optional (?) arguments" .
        "\nfusion [option]              Manager information" .

        "\n\n\033[4;32msettings commands\033[0m" .
        "\nconfig                       Show config entries" .
        "\nconfig [path=?value]         Set or drop config entries" .
        "\n---" .
        "\nexamples: " .
        "\nfusion config hub.apis.valvoid\\\.com.tokens=AAT-tBrEZ... (set by path)" .
        "\nfusion config hub.apis.valvoid\\\.com= (drop = set nothing to path)" .
        "\nfusion config (show config)" .
        "\n---" .
        "\nFor complex entries, it may be easier to edit the file directly." .
        "\nFusion validates this config like all others." .

        "\n\n\033[4;32mflag options\033[0m" .
        "\n-v | --version               Show current Fusion version".
        "\n-h | --help                  Show this information" .
        "\n-p | --paths                 Show root, config, state, and cache paths".
        "\n\n";

    exit($code);
}

/**
 * Loads lazy loadable.
 *
 * @param string $loadable Loadable.
 */
function loadLazyCode(string $loadable): void
{
    if (str_starts_with($loadable, "Valvoid\Fusion")) {
        $file = substr($loadable, 14);
        $file = str_replace('\\', '/', $file);
        $file = __DIR__ . "/src$file.php";

        if (file_exists($file))
            require $file;
    }
}

/**
 * Throws internal error.
 *
 * @throws InternalError Internal error.
 */
function throwError(string $message): void
{
    throw new InternalError($message);
}