#!/usr/bin/env php
<?php
/**
 * Fusion - PHP Package Manager
 * Copyright © Valvoid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

use Valvoid\Fusion\Fusion;
use Valvoid\Fusion\Log\Events\Errors\Error as InternalError;
use Valvoid\Fusion\Log\Events\Event;
use Valvoid\Fusion\Log\Events\Level;
use Valvoid\Fusion\Log\Serializers\Streams\Terminal\Terminal;
use Valvoid\Fusion\Options\Paths;
use Valvoid\Fusion\Options\Version;
use Valvoid\Fusion\Settings\Config\Config;
use Valvoid\Fusion\Wrappers\File;
use Valvoid\Fusion\Wrappers\Dir;
use Valvoid\Fusion\Wrappers\System;

try {
    $options = getopt("vhp", ["version", "help", "paths"]);

    if ($options)
        switch (array_key_first($options)) {
            case 'version':
            case 'v':
                require_once __DIR__ . "/src/Options/Version.php";
                require_once __DIR__ . "/src/Wrappers/File.php";

                $version = new Version(new File);

                echo "\n\033[4;32mFusion - PHP Package Manager\033[0m" .
                    "\nVersion $version->semver\n\n";
                exit;

            case 'paths':
            case 'p':
                require_once __DIR__ . "/src/Options/Paths.php";
                require_once __DIR__ . "/src/Wrappers/File.php";
                require_once __DIR__ . "/src/Wrappers/Dir.php";
                require_once __DIR__ . "/src/Wrappers/System.php";

                $paths = new Paths(new Dir, new File, new System);

                echo "\n\033[4;32mroot, config, state, and cache paths\033[0m" .
                    "\n$paths->path" .
                    "\n$paths->config" .
                    "\n$paths->state" .
                    "\n$paths->cache\n\n";
                exit;

            case 'help':
            case 'h': showHelp(0);
            default: showHelp();
        }

    // remove filename
    array_shift($argv);
    $argv = array_filter($argv, fn ($argument) =>

        // flag options only for now
        // drop all with dash
        $argument[0] !== '-');

    $arguments = [];
    $command = array_shift($argv) ??
        showHelp();

    // inflate inline config
    foreach ($argv as $argument) {
        $argumentParts = explode('=', $argument, 2);

        if (!$argumentParts[0])
            throwError(
                "Invalid \"$argument\" argument. An argument " .
                "must be a non-empty \"key=value\" entry."
            );

        $path = preg_split('/(?<!\\\\)\./', $argumentParts[0]);
        $argumentParts[1] ??= "";

        if ($path[0] != "dir" && $path[0] != "persistence" &&
            $path[0] != "log" && $path[0] != "hub")
            $path = ["tasks", $command, ...$path];

        // handle bool value
        if ($argumentParts[1] == "false")
            $argumentParts[1] = false;

        elseif ($argumentParts[1] == "true")
            $argumentParts[1] = true;

        // reset value
        elseif ($argumentParts[1] == "null")
            $argumentParts[1] = null;

        inflateArgumentValue($arguments, $path, $argumentParts[1]);
    }


    require_once __DIR__ . "/src/Fusion.php";

    Fusion::init($arguments);

    if (Fusion::manage($command) === false) {
        echo "\n\n";
        exit(1);
    }

// own CLI and fusion constructor loggable
} catch (Event $event) {
    require_once __DIR__ . "/src/Log/Events/Level.php";
    require_once __DIR__ . "/src/Log/Serializers/Streams/Stream.php";
    require_once __DIR__ . "/src/Log/Serializers/Streams/Terminal/Terminal.php";

    $terminal = new Terminal(["threshold" => Level::INFO]);

    $terminal->log(Level::ERROR, $event);
    echo "\n\n";
    exit(1);

// default
} catch (Exception $exception) {
    echo $exception->getMessage();
    echo $exception->getTraceAsString();
    echo "\n\n";
    exit(1);
}

echo "\n\n";
exit;

/**
 * Inflates inline argument value.
 *
 * @param array $config Pointer inside runtime config.
 * @param array $path Inline config path.
 * @param mixed $value Value.
 */
function inflateArgumentValue(mixed &$config, array $path, mixed $value): void
{
    $key = array_shift($path);
    $key = str_replace("\.", '.', "" . $key);

    if ($key) {
        if (!isset($config[$key]))
            $config[$key] = null;

        elseif (!is_array($config[$key]))
            $config[$key] = [
                $config[$key]
            ];

        inflateArgumentValue($config[$key], $path, $value);

    // extend
    } elseif (is_array($config))
        $config[] = $value;

    // add
    else $config = $value;
}

function showHelp(int $code = 1): void
{
    echo "\n\033[4;32musage\033[0m" .
        "\nfusion [command] ?args       Workload with optional (?) arguments" .
        "\nfusion [option]              Manager information" .

        "\n\n\033[4;32mflag options\033[0m" .
        "\n-v | --version               Show current Fusion version".
        "\n-h | --help                  Show this information" .
        "\n-p | --paths                 Show root, config, state, and cache paths".
        "\n\n";

    exit($code);
}

/**
 * Throws internal error.
 *
 * @throws InternalError Internal error.
 */
function throwError(string $message): void
{
    require_once __DIR__ . "/src/Log/Events/Event.php";
    require_once __DIR__ . "/src/Log/Events/Errors/Error.php";

    throw new InternalError($message);
}