<?php
// Auto-generated by Fusion package manager. 
// Do not modify.
return [
	'Valvoid\Fusion\Tests\Bus\BusTest' => '/tests/Bus/BusTest.php',
	'Valvoid\Fusion\Tests\Config\ConfigTest' => '/tests/Config/ConfigTest.php',
	'Valvoid\Fusion\Tests\Dir\ConfigMock' => '/tests/Dir/ConfigMock.php',
	'Valvoid\Fusion\Tests\Dir\DirTest' => '/tests/Dir/DirTest.php',
	'Valvoid\Fusion\Tests\Hub\Cache\CacheTest' => '/tests/Hub/Cache/CacheTest.php',
	'Valvoid\Fusion\Tests\Hub\ConfigMock' => '/tests/Hub/ConfigMock.php',
	'Valvoid\Fusion\Tests\Hub\HubTest' => '/tests/Hub/HubTest.php',
	'Valvoid\Fusion\Tests\Log\ConfigMock' => '/tests/Log/ConfigMock.php',
	'Valvoid\Fusion\Tests\Log\LogTest' => '/tests/Log/LogTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\ClauseTest' => '/tests/Tasks/Build/SAT/ClauseTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\GraphTest' => '/tests/Tasks/Build/SAT/GraphTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\SolverTest' => '/tests/Tasks/Build/SAT/SolverTest.php',
	'Valvoid\Fusion\Tests\Tasks\Categorize\CategorizeTest' => '/tests/Tasks/Categorize/CategorizeTest.php',
	'Valvoid\Fusion\Tests\Tasks\Categorize\Mocks\LogMock' => '/tests/Tasks/Categorize/Mocks/LogMock.php',
	'Valvoid\Fusion\Tests\Tasks\Categorize\Mocks\MetadataMock' => '/tests/Tasks/Categorize/Mocks/MetadataMock.php',
	'Valvoid\Fusion\Tests\Tasks\GroupTest' => '/tests/Tasks/GroupTest.php',
	'Valvoid\Fusion\Tests\Test' => '/tests/Test.php',
	'Valvoid\Fusion\Tests\Util\Pattern\InterpreterTest' => '/tests/Util/Pattern/InterpreterTest.php',
	'Valvoid\Fusion\Tests\Util\Version\InterpreterTest' => '/tests/Util/Version/InterpreterTest.php',
];