<?php
// Auto-generated by Fusion package manager. 
// Do not modify.
return [
	'Valvoid\Fusion\Tests\Hub\Cache\CacheTest' => '/tests/Hub/Cache/CacheTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\ClauseTest' => '/tests/Tasks/Build/SAT/ClauseTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\GraphTest' => '/tests/Tasks/Build/SAT/GraphTest.php',
	'Valvoid\Fusion\Tests\Tasks\Build\SAT\SolverTest' => '/tests/Tasks/Build/SAT/SolverTest.php',
	'Valvoid\Fusion\Tests\Test' => '/tests/Test.php',
	'Valvoid\Fusion\Tests\Util\Pattern\InterpreterTest' => '/tests/Util/Pattern/InterpreterTest.php',
	'Valvoid\Fusion\Tests\Util\Version\InterpreterTest' => '/tests/Util/Version/InterpreterTest.php',
];